# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            tagtog
tagline:          'A text annotation tool to train AI'
description:      'Official documentation for <a href="https://tagtog.net">tagtog</a>'
url:              https://docs.tagtog.net
baseurl:          # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
groups:
  - id: webapp
    name: Web Application
  - id: api
    name: API
  - id: search
    name: Concept Search
  - id: formats
    name: Formats supported

author:
  name:           'tagtog sp.z.o.o'
  url:            https://twitter.com/tagtog_net

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            1.0.0
sidebar_home_link:  true
search_page:   false
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
github:
  repo:             https://github.com/tagtog/

defaults:
- scope:
    path: "assets/img"
  values:
    image: true